name: "Airspace traffic aggregator"
on:
  schedule: 
    - cron: '*/15 * * * *'

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: "Install node"
        uses: actions/setup-node@v1
      - name: "Install dependencies"
        run: npm install
      - name: "Run code"
        run: node index.js
        env:
          AIRPORT: 'BUD'
          MAX_ALTITUDE_FT: '15000'
          MAX_DISTANCE_KM: '50'
      - name: "Clean up"
        run: rm -f package-lock.json
      - name: "Store data"
        uses: stefanzweifel/git-auto-commit-action@v2.5.0
        with:
          commit_message: '[BUD] Traffic scan'
          branch: master
          file_pattern: airports/BUD/*.csv
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
